using System;
using System.Text.RegularExpressions;
using NUnit.Framework;
using Unity.Services.Multiplayer;
using UnityEngine;
using UnityEngine.TestTools;
using TicTacFade.Game;
using TicTacFade.Net;

namespace TicTacFade.PlayModeTests
{
    /// <summary>
    /// Pure-logic tests for the Net layer: join-code format and SDK error
    /// mapping. They live in the PlayMode assembly only because that is the
    /// test assembly that already references TicTacFade.Net; they need no
    /// scene or frames.
    /// </summary>
    public class NetSessionRulesTests
    {
        [TestCase("BCD678")]
        [TestCase("LD7987")]            // generated by the real service
        [TestCase("B6DRRR")]            // generated by the real service
        [TestCase("6789BCDFGHJK")]      // 12 chars, the maximum
        public void JoinCodeFormat_CodeInAlphabetWithValidLength_IsWellFormed(string code)
        {
            Assert.IsTrue(JoinCodeFormat.IsWellFormed(code));
        }

        [TestCase("ZZZZZZ")]            // rejected by the real service: 'Z' is not in the alphabet
        [TestCase("ABC123")]            // alphanumeric but outside the alphabet
        [TestCase("BCD67")]             // 5 chars, too short
        [TestCase("6789BCDFGHJKL")]     // 13 chars, too long
        [TestCase("bcd678")]            // not normalized: callers upper-case first
        [TestCase("")]
        [TestCase(null)]
        public void JoinCodeFormat_CodeOutsideAlphabetOrLength_IsNotWellFormed(string code)
        {
            Assert.IsFalse(JoinCodeFormat.IsWellFormed(code));
        }

        [TestCase("LD7987")]
        [TestCase("b6drrr")]            // normalized before checking
        public void CheckGeneratedCode_CodeAcceptedLocally_PassesWithoutLogging(string code)
        {
            Assert.IsTrue(JoinCodeFormat.CheckGeneratedCode(code));
            LogAssert.NoUnexpectedReceived();
        }

        [Test]
        public void CheckGeneratedCode_ServiceCodeRejectedLocally_LogsFormatChangedError()
        {
            // Simulates the service starting to generate codes our rule
            // rejects (e.g. a new letter in the alphabet).
            LogAssert.Expect(LogType.Error, new Regex("room code format changed.*'AB12CD'"));

            Assert.IsFalse(JoinCodeFormat.CheckGeneratedCode("AB12CD"));
        }

        [Test]
        public void MapJoin_ServiceCodeFormatError_IsInvalidCode()
        {
            // Exact message returned by the real service for "ZZZZZZ".
            var e = new SessionException(
                "lobby code 'ZZZZZZ' contains an invalid character 'Z' (U+005A) at index 0", SessionError.Unknown, null);

            Assert.AreEqual(SessionFailure.InvalidCode, SessionFailureMapper.MapJoin(e));
        }

        [Test]
        public void MapJoin_SessionNotFound_IsInvalidCode()
        {
            var e = new SessionException("lobby not found", SessionError.SessionNotFound, null);

            Assert.AreEqual(SessionFailure.InvalidCode, SessionFailureMapper.MapJoin(e));
        }

        [Test]
        public void MapJoin_UnspecifiedRefusal_IsJoinRejected()
        {
            var e = new SessionException("lobby is full", SessionError.Unknown, null);

            Assert.AreEqual(SessionFailure.JoinRejected, SessionFailureMapper.MapJoin(e));
        }

        [Test]
        public void Map_UnknownSessionErrorOutsideJoin_StaysUnknown()
        {
            var e = new SessionException("lobby code 'ZZZZZZ' contains an invalid character", SessionError.Unknown, null);

            Assert.AreEqual(SessionFailure.Unknown, SessionFailureMapper.Map(e));
        }

        [Test]
        public void Map_ExceptionWithoutSdkCause_IsUnknownNotNone()
        {
            Assert.AreEqual(SessionFailure.Unknown, SessionFailureMapper.Map(new InvalidOperationException("boom")));
        }
    }
}
